#!/usr/bin/env python

import argparse
import codegen

if __name__ == '__main__':
    argp = argparse.ArgumentParser(description='A microcode assembler for the n16 and n32')
    argp.add_argument('input_files', nargs='+')
    argp.add_argument('-o', type=str, default='u')
    args = argp.parse_args()

    codegen.parse_and_write(args)
